### ISSUE TITLE
Error: Metadata version mismatch for module

### ISSUE THREAD

**Issue by jnavarro1512** [chymz/ng2-ckeditor#177]
When I install the package I have problems when running ng serve:

ERROR in Error: Metadata version mismatch for module C:/Users/jnavarro/Documents/AngularProjects/frontendsismonitor_/node_modules/ng2-ckeditor/lib/ng2-ckeditor.d.ts, found version 4, expected 3, resolving symbol AppModule in C:/Users/jnavarro/Documents/AngularProjects/frontendsismonitor_/src/app/app.module.ts, resolving symbol AppModule in C:/Users/jnavarro/Documents/AngularProjects/frontendsismonitor_/src/app/app.module.ts
    at Error (native)
    at syntaxError (C:\Users\jnavarro\Documents\AngularProjects\frontendsismonitor_\node_modules\@angular\compiler\bundles\compiler.umd.js:1729:34)
    at simplifyInContext (C:\Users\jnavarro\Documents\AngularProjects\frontendsismonitor_\node_modules\@angular\compiler\bundles\compiler.umd.js:24979:23)
    at StaticReflector.simplify (C:\Users\jnavarro\Documents\AngularProjects\frontendsismonitor_\node_modules\@angular\compiler\bundles\compiler.umd.js:24991:13)
    at StaticReflector.annotations (C:\Users\jnavarro\Documents\AngularProjects\frontendsismonitor_\node_modules\@angular\compiler\bundles\compiler.umd.js:24418:41)
    at _getNgModuleMetadata (C:\Users\jnavarro\Documents\AngularProjects\frontendsismonitor_\node_modules\@angular\compiler-cli\src\ngtools_impl.js:138:31)
    at _extractLazyRoutesFromStaticModule (C:\Users\jnavarro\Documents\AngularProjects\frontendsismonitor_\node_modules\@angular\compiler-cli\src\ngtools_impl.js:109:26)
    at Object.listLazyRoutesOfModule (C:\Users\jnavarro\Documents\AngularProjects\frontendsismonitor_\node_modules\@angular\compiler-cli\src\ngtools_impl.js:53:22)
    at Function.NgTools_InternalApi_NG_2.listLazyRoutes (C:\Users\jnavarro\Documents\AngularProjects\frontendsismonitor_\node_modules\@angular\compiler-cli\src\ngtools_api.js:91:39)
    at AotPlugin._getLazyRoutesFromNgtools (C:\Users\jnavarro\Documents\AngularProjects\frontendsismonitor_\node_modules\@ngtools\webpack\src\plugin.js:241:66)
    at _donePromise.Promise.resolve.then.then.then.then.then (C:\Users\jnavarro\Documents\AngularProjects\frontendsismonitor_\node_modules\@ngtools\webpack\src\plugin.js:495:24)
    at process._tickCallback (internal/process/next_tick.js:109:7)

**Comment by matosconsulting** [comment]
+1. Looks like some recent breaking changes. If you downgrade to version 1.1.9 you'll be able to get past this.

**Comment by jnavarro1512** [comment]
Intendant installing version 1.1.5 and can not solve the problem

**Comment by jnavarro1512** [comment]
I solved it by updating the Angular version from 4 to 5:

"@angular/cdk": "^5.0.0-rc0",
"@angular/common": "^5.0.0",
"@angular/compiler": "^5.0.0",
"@angular/core": "^5.0.0",
"@angular/forms": "^5.0.0",
"@angular/http": "^5.0.0",
"@angular/material": "^5.0.0-rc0",
"@angular/platform-browser": "^5.0.0",
"@angular/platform-browser-dynamic": "^5.0.0",
"@angular/router": "^5.0.0",
"@angular/cli": "^1.5.0",
"@angular/compiler-cli": "^5.0.0",
"@angular/language-service": "^5.0.0",

**Comment by yogesh-sadhokar** [comment]
ERROR in Metadata version mismatch for module /home/deepak/TAMSWorkspace/PaladionTAMSUI/angular/node_modules/ng2-ckeditor/lib/ng2-ckeditor.d.ts, found version 4, expected 3, resolving symbol AppModule in /home/deepak/TAMSWorkspace/PaladionTAMSUI/angular/src/app/app.module.ts, resolving symbol AppModule in /home/deepak/TAMSWorkspace/PaladionTAMSUI/angular/src/app/app.module.ts

webpack: Failed to compile.

**Comment by yogesh-sadhokar** [comment]
{
  "name": "paladion",
  "version": "1.0.0",
  "description": "This project was generated with [Angular CLI](https://github.com/angular/angular-cli) version 1.3.2.",
  "main": "karma.conf.js",
  "scripts": {
    "ng": "ng",
    "start": "ng serve",
    "build": "ng build",
    "test": "ng test",
    "lint": "ng lint",
    "e2e": "ng e2e"
  },
  "author": "",
  "license": "ISC",
  "private": true,
  "dependencies": {
    "@angular/animations": "^4.3.6",
    "@angular/cdk": "^2.0.0-beta.10",
    "@angular/common": "^4.4.6",
    "@angular/compiler": "^4.2.4",
    "@angular/core": "^4.4.6",
    "@angular/forms": "^4.4.6",
    "@angular/http": "^4.2.4",
    "@angular/material": "^2.0.0-beta.10",
    "@angular/platform-browser": "^4.2.4",
    "@angular/platform-browser-dynamic": "^4.2.4",
    "@angular/router": "^4.2.4",
    "@cedx/ngx-webstorage": "^1.2.0",
    "angular2-cool-storage": "^3.1.0",
    "angular2-focus": "^1.1.0",
    "ckeditor": "^4.7.3",
    "classlist.js": "^1.1.20150312",
    "core-js": "^2.4.1",
    "jquery": "^3.2.1",
    "lodash": "^4.17.4",
    "ng2-ckeditor": "^1.1.9",
    "ng2-toastr": "^4.1.2",
    "ng2-toasty": "^4.0.3",
    "ngx-perfect-scrollbar": "^4.6.3",
    "rxjs": "^5.4.2",
    "tinymce": "^4.6.4",
    "underscore": "^1.8.3",
    "zone.js": "^0.8.14"
  },
  "devDependencies": {
    "@angular/cli": "1.3.2",
    "@angular/compiler-cli": "^4.2.4",
    "@angular/language-service": "^4.2.4",
    "@types/jasmine": "~2.5.53",
    "@types/jasminewd2": "~2.0.2",
    "@types/node": "~6.0.60",
    "codelyzer": "~3.1.1",
    "jasmine-core": "~2.6.2",
    "jasmine-spec-reporter": "~4.1.0",
    "karma": "~1.7.0",
    "karma-chrome-launcher": "~2.1.1",
    "karma-cli": "~1.0.1",
    "karma-coverage-istanbul-reporter": "^1.2.1",
    "karma-jasmine": "~1.1.0",
    "karma-jasmine-html-reporter": "^0.2.2",
    "protractor": "~5.1.2",
    "ts-node": "~3.2.0",
    "tslint": "~5.3.2",
    "typescript": "~2.3.3"
  }
}

**Comment by yogesh-sadhokar** [comment]
Need a quick solution for this without upgrading to angular 4 or 5

**Comment by rajeshK88** [comment]
try to use 
"ng2-ckeditor": "1.1.9",
instead 
"ng2-ckeditor": "^1.1.9",

**Comment by 6matko** [comment]
This worked for me.

**Comment by Ruben1102** [comment]
"ng2-ckeditor":"1.1.9" works for me.(angular 4.*).

**Comment by chiragms** [comment]
> try to use
> "ng2-ckeditor": "1.1.9",
> instead
> "ng2-ckeditor": "^1.1.9",

My project has Angular 4.2.4 and this did the trick for me. 
Thanks bro, Saved me insane amount of time. @rajeshK88 You're a genius bro!

**Comment by simthera** [comment]
try to use
"ng2-ckeditor": "1.1.9",
instead
"ng2-ckeditor": "^1.1.9",

Also worked for me. thanks @rajeshK88 !!
