### ISSUE TITLE
TypeError: Cannot set property 'dir' of undefined

### ISSUE THREAD

**Issue by binhphamv** [chymz/ng2-ckeditor#190]
I am geting errors when change 
<script src="https://cdn.ckeditor.com/4.5.11/full/ckeditor.js"></script>
 to
<script src="/assets/libs/ckeditor/ckeditor.js"></script>

can u provide any solution for this?

**Comment by kzimny** [comment]
What kind of error? Can you provide more information please and you ng2-ckeditor configuration? Are you using additional plugins?

**Comment by binhphamv** [comment]
@kzimny 
i'm using angular webpack bundler in project.
If i using cdn :<script src="https://cdn.ckeditor.com/4.5.11/full/ckeditor.js"></script> include to indext.htm , ng2-ckeditor is worked, but when i change to 
<script src="/assets/libs/ckeditor/ckeditor.js"></script>
i am getting errors :
TypeError: Cannot set property 'dir' of undefined
    at Object.d (http://localhost:3000/assets/libs/ckeditor/ckeditor.js:230:51)
    at e (http://localhost:3000/assets/libs/ckeditor/ckeditor.js:231:177)
    at Array.A (http://localhost:3000/assets/libs/ckeditor/ckeditor.js:231:332)
    at r (http://localhost:3000/assets/libs/ckeditor/ckeditor.js:231:416)
    at HTMLScriptElement.CKEDITOR.env.ie.e.$.onerror [as __zone_symbol__ON_PROPERTYerror] (http://localhost:3000/assets/libs/ckeditor/ckeditor.js:232:363)

**Comment by kzimny** [comment]
I'm afraid that I can not say much more without knowing your ckeditor configuration? Are you using additional plugins? Please post the ckeditor.js configuration:

```js
CKEDITOR.editorConfig = function( config ) {
	// Define changes to default configuration here. For example:
	config.language = 'en';
	config.uiColor = '#AADC6E';
}; 
```
and angular ckeditor configuration:

```ts
ckeConfig: any;

  ngOnInit() {
                this.ckeConfig = {
                    allowedContent: true,
                    extraPlugins: "divarea"
                }; 
  }
```

**Comment by binhphamv** [comment]
@kzimny 
my config: 
<pre>
private model: any = {
        config: {
            toolbar: [
                ['boldBtn', 'bulletedListBtn',
                'justifyLeftBtn', 'justifyCenterBtn', 'justifyRightBtn']  // custom button
            ],
            removePlugins: 'magicline, contextmenu, liststyle, tabletools',
            contentsCss: `.cke_editable  { 
                background-color: #f6f7fb; 
                -webkit-border-radius: 17px !important;
                -moz-border-radius: 17px !important;
                border-radius: 17px !important;
                border: 0; outline: none;
                font-size: 14px;
            }`,
        }
    };
</pre>
error details: 
GET http://localhost:3000/assets/libs/ckeditor/config.js?t=G87E net::ERR_ABORTED    ckeditor.js:84 
GET http://localhost:3000/assets/libs/ckeditor/skins/moono/editor.css?t=G87E net::ERR_ABORTED  ckeditor.js:84 
GET http://localhost:3000/assets/libs/ckeditor/lang/vi.js?t=G87E net::ERR_ABORTED ckeditor.js:84 
errorHandler.service.ts:16 TypeError: Cannot set property 'dir' of undefined 
    at Object.d (http://localhost:3000/assets/libs/ckeditor/ckeditor.js:230:51)
    at e (http://localhost:3000/assets/libs/ckeditor/ckeditor.js:231:177)
    at Array.A (http://localhost:3000/assets/libs/ckeditor/ckeditor.js:231:332)
    at r (http://localhost:3000/assets/libs/ckeditor/ckeditor.js:231:416)
    at HTMLScriptElement.CKEDITOR.env.ie.e.$.onerror [as __zone_symbol__ON_PROPERTYerror] (http://localhost:3000/assets/libs/ckeditor/ckeditor.js:232:363)
    at HTMLScriptElement.wrapFn (http://localhost:3000/polyfills.bundle.js:18436:39)
    at ZoneDelegate.invokeTask (http://localhost:3000/polyfills.bundle.js:17695:31)
    at Object.onInvokeTask (http://localhost:3000/main.bundle.js:9731:33)
    at ZoneDelegate.invokeTask (http://localhost:3000/polyfills.bundle.js:17694:36)
    at Zone.runTask (http://localhost:3000/polyfills.bundle.js:17462:47)
    at ZoneTask.invokeTask [as invoke] (http://localhost:3000/polyfills.bundle.js:17769:34)
    at invokeTask (http://localhost:3000/polyfills.bundle.js:18810:14)
    at HTMLScriptElement.globalZoneAwareCallback (http://localhost:3000/polyfills.bundle.js:18836:17)
    at ____________________Elapsed_20_ms__At__Sun_Jan_21_2018_18_14_34_GMT_0700__SE_Asia_Standard_Time_ (http://localhost)
    at Object.onScheduleTask (http://localhost:3000/polyfills.bundle.js:20482:22)
    at ZoneDelegate.scheduleTask (http://localhost:3000/polyfills.bundle.js:17675:51)
    at Object.onScheduleTask (http://localhost:3000/polyfills.bundle.js:17571:29)
    at ZoneDelegate.scheduleTask (http://localhost:3000/polyfills.bundle.js:17675:51)
    at Zone.scheduleTask (http://localhost:3000/polyfills.bundle.js:17506:43)
    at Zone.scheduleEventTask (http://localhost:3000/polyfills.bundle.js:17532:25)
    at HTMLScriptElement.addEventListener (http://localhost:3000/polyfills.bundle.js:19102:33)
    at HTMLScriptElement.desc.set [as onerror] (http://localhost:3000/polyfills.bundle.js:18486:20)

**Comment by kzimny** [comment]
remove the line:
```ts
removePlugins: 'magicline, contextmenu, liststyle, tabletools',
```
and try again

**Comment by kzimny** [comment]
try the following:
1. [download ](https://download.cksource.com/CKEditor/CKEditor/CKEditor%204.5.11/ckeditor_4.5.11_standard.zip)ckeditor without additional plugins. 
2. set the path to ckeditor.js to another:
```html 
<script src="ckeditor/ckeditor.js"></script>
```
exact the same configuration work on my side. This error means:
GET http://localhost:3000/assets/libs/ckeditor/config.js?t=G87E net::ERR_ABORTED ckeditor.js:84

that ckeditor is looking for ressources which are not available.

**Comment by kzimny** [comment]
No activity

**Comment by mariohmol** [comment]
In my case was missing the lang

` <script src="/assets/ckeditor/lang/pt-br.js"></script>`
