### ISSUE TITLE
Setup not working in Angular Seed

### ISSUE THREAD

**Issue by mattisebastian** [chymz/ng2-ckeditor#195]
Hi,

I am trying to use ng2-ckeditor in angular seed.
From the setup guide and [this issue](https://github.com/chymz/ng2-ckeditor/issues/67) I put this in my 

1. index.html:

`  <script src="https://cdn.ckeditor.com/4.5.11/full/ckeditor.js"></script>`

and

2. project.config.ts:

```javascript  
      this.NPM_DEPENDENCIES = [
      ...this.NPM_DEPENDENCIES,
      ...
      {src: 'ng2-ckeditor/lib/ng2-ckeditor.js', inject: 'libs'},
```

3. I am adding the module in my angular module:

```javascript

import { CKEditorModule } from 'ng2-ckeditor'

@NgModule({
  imports: [..., CKEditorModule],
```

I get this error:

```

ng2-ckeditor.js?1518192897399:2 Uncaught ReferenceError: exports is not defined
    at ng2-ckeditor.js?1518192897399:2
(anonymous) @ ng2-ckeditor.js?1518192897399:2
(index):60 SyntaxError: Unexpected token <
    at eval (<anonymous>)
    at evaluate (http://localhost:1336/node_modules/systemjs/dist/system.src.js?1518192897396:2818:16)
    at http://localhost:1336/node_modules/systemjs/dist/system.src.js?1518192897396:3621:21
    at dynamicExecute (http://localhost:1336/node_modules/systemjs/dist/system.src.js?1518192897396:1142:26)
    at doEvaluate (http://localhost:1336/node_modules/systemjs/dist/system.src.js?1518192897396:1089:13)
    at ensureEvaluate (http://localhost:1336/node_modules/systemjs/dist/system.src.js?1518192897396:997:13)
    at http://localhost:1336/node_modules/systemjs/dist/system.src.js?1518192897396:1015:20
    at Object.eval (http://localhost:1336/app/courses/courses.module.js:24:24)
    at eval (http://localhost:1336/app/courses/courses.module.js:39:4)
    at eval (http://localhost:1336/app/courses/courses.module.js:40:3) Not expecting this error? Report it at https://github.com/mgechev/angular-seed/issues
```
Any idea what to add here?

Thank you and best regards
Matti

**Comment by kzimny** [comment]
1. delete the {src: 'ng2-ckeditor/lib/ng2-ckeditor.js', inject: 'libs'} entry in this.NPM_DEPENDENCIES 

2. add package to additionalVariables as follow:

```ts
        // Add packages (e.g. ng2-translate)
        const additionalPackages: ExtendPackages[] = [
        {
            name: 'ng2-ckeditor',
            path: 'node_modules/ng2-ckeditor',
            packageMeta: {
                defaultExtension: 'js',
                main: 'lib/ng2-ckeditor'
            }
        }];
```

ng2-ckeditor is working fine with angular-seed project.

**Comment by mattisebastian** [comment]
Thank you, I should've read the guide more carefully...
