### ISSUE TITLE
For angular 4/5 getting error - Metadata version mismatch for module /node_modules/ng2-ckeditor/lib/ng2-ckeditor.d.ts, found version 4, expected 3

### ISSUE THREAD

**Issue by priraut88** [chymz/ng2-ckeditor#235]
I was trying to integrate ng2-ckeditor with angular 4 application. 

Following link : [https://www.npmjs.com/package/ng2-ckeditor]

Followed these steps : 
use npm install ng2-ckeditor to install the ng2-ckeditor
in your app.module.ts, you should have something like this
import { BrowserModule } from '@angular/platform-browser';
import { NgModule } from '@angular/core';
import { FormsModule } from '@angular/forms';
import { CKEditorModule } from 'ng2-ckeditor';
import { AppComponent } from './app.component';

@NgModule({
  declarations: [
    AppComponent
  ],

  imports: [
    BrowserModule,
    CKEditorModule,
    FormsModule
  ],

  providers: [],

  bootstrap: [AppComponent]
})

export class AppModule { }
and then

in your index.html add
<script src="https://cdn.ckeditor.com/4.5.11/full/ckeditor.js"></script>

current package version is - "ng2-ckeditor": "^1.2.1"

But while execution it is giving me below error :

ERROR in Error: Metadata version mismatch for module /node_modules/ng2-ckeditor/lib/ng2-ckeditor.d.ts, found version 4, expected 3, resolving symbol 
AppModule in /src/app/app.module.ts, resolving symbol AppModule in /src/app/app.module.ts
    at syntaxError (\node_modules\@angular\compiler\bundles\compiler.umd.js:1729:34)
    at simplifyInContext (\node_modules\@angular\compiler\bundles\compiler.umd.js:24979:23)
    at StaticReflector.simplify (\node_modules\@angular\compiler\bundles\compiler.umd.js:24991:13)
    at StaticReflector.annotations (\node_modules\@angular\compiler\bundles\compiler.umd.js:24418:41)
    at _getNgModuleMetadata (\node_modules\@angular\compiler-cli\src\ngtools_impl.js:138:31)
    at _extractLazyRoutesFromStaticModule (\node_modules\@angular\compiler-cli\src\ngtools_impl.js:109:26)
    at Object.listLazyRoutesOfModule (\node_modules\@angular\compiler-cli\src\ngtools_impl.js:53:22)
    at Function.NgTools_InternalApi_NG_2.listLazyRoutes (\node_modules\@angular\compiler-cli\src\ngtools_api.js:91:39)
    at AotPlugin._getLazyRoutesFromNgtools (\node_modules\@ngtools\webpack\src\plugin.js:207:44)
    at _donePromise.Promise.resolve.then.then.then.then.then (\node_modules\@ngtools\webpack\src\plugin.js:443:24)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)

@kzimny  Can you tell me quick solution for this.

**Comment by kzimny** [comment]
The error does not come from ng2-ckeditor. It seems that there is a version conflict in your `@angular/*` packages as described [here](https://stackoverflow.com/questions/47115649/metadata-version-mismatch-with-angular-4). Can you update to angular 5?

**Comment by priraut88** [comment]
@kzimny  Yes, it was because version conflicts. Thanks for your quick input.
