### ISSUE TITLE
Using ng2-ckeditor with latest Angular CLI version (7.0.0-beta.4) Throw error

### ISSUE THREAD

**Issue by naveedahmed1** [chymz/ng2-ckeditor#246]
Using ng2-ckeditor with latest Angular CLI version (7.0.0-beta.4) throws below error:

```
ERROR in ./node_modules/ng2-ckeditor/lib/src/ckeditor.component.ngfactory.js
Module build failed (from ./node_modules/@ngtools/webpack/src/index.js):
Error: D:\Project\node_modules\ng2-ckeditor\lib\src\ckeditor.component.ngfactory.js is missing from the TypeScript compilation. Please make sure it is in your tsconfig via the 'files' or 'include' property.
The missing file seems to be part of a third party library. TS files in published libraries are often a sign of a badly packaged library. Please open an issue in the library repository to alert its author and ask them to package the library using the Angular Package Format (https://goo.gl/jB3GVv).
    at AngularCompilerPlugin.getCompiledFile (D:\Project\node_modules\@ngtools\webpack\src\angular_compiler_plugin.js:741:23)
    at plugin.done.then (D:\Project\node_modules\@ngtools\webpack\src\loader.js:41:31)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
```

**Comment by aniruddhadas9** [comment]
I am also facing the same issue when upgraded to `angular@7.0.0-beta.6` and below is the error:

```
ERROR in ./node_modules/ng2-ckeditor/lib/src/ckeditor.component.ngfactory.js
Module build failed (from ./node_modules/@ngtools/webpack/src/index.js):
Error:./node_modules/ng2-ckeditor/lib/src/ckeditor.component.ngfactory.js is missing from the TypeScript compilation. Please make sure it is in your tsconfig via the 'files' or 'include' property.
The missing file seems to be part of a third party library. TS files in published libraries are often a sign of a badly packaged library. Please open an issue in the library repository to alert its author and ask them to package the library using the Angular Package Format (https://goo.gl/jB3GVv).
    at AngularCompilerPlugin.getCompiledFile (./node_modules/@ngtools/webpack/src/angular_compiler_plugin.js:741:23)
    at plugin.done.then (./node_modules/@ngtools/webpack/src/loader.js:41:31)
    at process._tickCallback (internal/process/next_tick.js:68:7)

```

**Comment by kzimny** [comment]
package.json has been changed in [1.2.2 version](https://github.com/chymz/ng2-ckeditor/commit/be96bb2ab8e17fdf473a916293f76a6203c58db8).
