### ISSUE TITLE
TypeError: Cannot read properties of undefined (reading 'create')

### ISSUE THREAD

**Issue by monis-dineout** [chymz/ng2-ckeditor#326]
I get this error message in the browser console

`ERROR Error: Uncaught (in promise): TypeError: Cannot read properties of undefined (reading 'create')
TypeError: Cannot read properties of undefined (reading 'create')
    at CKEditorComponent.<anonymous> (vendor.10e5241a470cf196eb58.js:133204:71)
    at Generator.next (<anonymous>)
    at vendor.10e5241a470cf196eb58.js:448451:71
    at new ZoneAwarePromise (polyfills.f4513d817183eb69248a.js:1182:33)
    at __awaiter (vendor.10e5241a470cf196eb58.js:448447:12)
    at vendor.10e5241a470cf196eb58.js:133201:74
    at ZoneDelegate.invoke (polyfills.f4513d817183eb69248a.js:586:30)
    at Zone.run (polyfills.f4513d817183eb69248a.js:345:47)
    at NgZone.runOutsideAngular (vendor.10e5241a470cf196eb58.js:80434:91)
    at CKEditorComponent.<anonymous> (vendor.10e5241a470cf196eb58.js:133198:32)
    at resolvePromise (polyfills.f4513d817183eb69248a.js:1020:39)
    at resolvePromise (polyfills.f4513d817183eb69248a.js:972:21)
    at polyfills.f4513d817183eb69248a.js:1082:21
    at ZoneDelegate.invokeTask (polyfills.f4513d817183eb69248a.js:621:35)
    at Object.onInvokeTask (vendor.10e5241a470cf196eb58.js:80523:33)
    at ZoneDelegate.invokeTask (polyfills.f4513d817183eb69248a.js:620:40)
    at Zone.runTask (polyfills.f4513d817183eb69248a.js:389:51)
    at drainMicroTaskQueue (polyfills.f4513d817183eb69248a.js:791:39)
    at ZoneTask.invokeTask [as invoke] (polyfills.f4513d817183eb69248a.js:706:25)
    at invokeTask (polyfills.f4513d817183eb69248a.js:1843:18)`

**Comment by kzimny** [comment]
Please check the implementation on [stackblitz](https://stackblitz.com/edit/ng2-ckeditor)
