### ISSUE TITLE
 self.context.onReady is not a function and self.context.onChange is not a function

### ISSUE THREAD

**Issue by codyburleson** [chymz/ng2-ckeditor#42]
I'm getting `self.context.onReady is not a function` and  `self.context.onChange is not a function`

Any ideas? 

Use is:

```
<ckeditor
	[(ngModel)]="model.body"
	[config]="{uiColor: '#99000'}"
	(change)="onChange($event)"
	(ready)="onReady($event)"
	debounce="500" name="body">
</ckeditor>
```

Exception is:

```
zone.js:140 Uncaught EXCEPTION: Error in ./BlogPostFormComponent class BlogPostFormComponent - inline template:56:3
ORIGINAL EXCEPTION: TypeError: self.context.onReady is not a function
ORIGINAL STACKTRACE:
TypeError: self.context.onReady is not a function
    at DebugAppView._View_BlogPostFormComponent0._handle_ready_53_2 (BlogPostFormComponent.ngfactory.js:1039:28)
    at eval (http://localhost:8045/jspm_packages/npm/@angular/core@2.0.0-rc.5/src/linker/view.js:381:24)
    at SafeSubscriber.schedulerFn [as _next] (http://localhost:8045/jspm_packages/npm/@angular/core@2.0.0-rc.5/src/facade/async.js:102:54)
    at SafeSubscriber.__tryOrUnsub (http://localhost:8045/jspm_packages/npm/rxjs@5.0.0-beta.6/Subscriber.js:225:16)
    at SafeSubscriber.next (http://localhost:8045/jspm_packages/npm/rxjs@5.0.0-beta.6/Subscriber.js:174:22)
    at Subscriber._next (http://localhost:8045/jspm_packages/npm/rxjs@5.0.0-beta.6/Subscriber.js:124:26)
    at Subscriber.next (http://localhost:8045/jspm_packages/npm/rxjs@5.0.0-beta.6/Subscriber.js:88:18)
    at EventEmitter.Subject._finalNext (http://localhost:8045/jspm_packages/npm/rxjs@5.0.0-beta.6/Subject.js:128:30)
    at EventEmitter.Subject._next (http://localhost:8045/jspm_packages/npm/rxjs@5.0.0-beta.6/Subject.js:120:18)
    at EventEmitter.Subject.next (http://localhost:8045/jspm_packages/npm/rxjs@5.0.0-beta.6/Subject.js:77:14)
ERROR CONTEXT:
[object Object]Zone.runTask @ zone.js:140ZoneTask.invoke @ zone.js:304
zone.js:140 Uncaught EXCEPTION: Error in ./BlogPostFormComponent class BlogPostFormComponent - inline template:55:3
ORIGINAL EXCEPTION: TypeError: self.context.onChange is not a function
ORIGINAL STACKTRACE:
TypeError: self.context.onChange is not a function
    at DebugAppView._View_BlogPostFormComponent0._handle_change_53_1 (BlogPostFormComponent.ngfactory.js:1032:28)
    at eval (http://localhost:8045/jspm_packages/npm/@angular/core@2.0.0-rc.5/src/linker/view.js:381:24)
    at SafeSubscriber.schedulerFn [as _next] (http://localhost:8045/jspm_packages/npm/@angular/core@2.0.0-rc.5/src/facade/async.js:102:54)
    at SafeSubscriber.__tryOrUnsub (http://localhost:8045/jspm_packages/npm/rxjs@5.0.0-beta.6/Subscriber.js:225:16)
    at SafeSubscriber.next (http://localhost:8045/jspm_packages/npm/rxjs@5.0.0-beta.6/Subscriber.js:174:22)
    at Subscriber._next (http://localhost:8045/jspm_packages/npm/rxjs@5.0.0-beta.6/Subscriber.js:124:26)
    at Subscriber.next (http://localhost:8045/jspm_packages/npm/rxjs@5.0.0-beta.6/Subscriber.js:88:18)
    at EventEmitter.Subject._finalNext (http://localhost:8045/jspm_packages/npm/rxjs@5.0.0-beta.6/Subject.js:128:30)
    at EventEmitter.Subject._next (http://localhost:8045/jspm_packages/npm/rxjs@5.0.0-beta.6/Subject.js:120:18)
    at EventEmitter.Subject.next (http://localhost:8045/jspm_packages/npm/rxjs@5.0.0-beta.6/Subject.js:77:14)
ERROR CONTEXT:
[object Object]
```

**Comment by 7Hd** [comment]
this maybe can use
```HTML
<ckeditor
    [(ngModel)]="model.body"
    [config]="{uiColor: '#99000'}"
    debounce="500" name="body">
</ckeditor>
```

**Comment by codyburleson** [comment]
Yeah - that works enough for my needs. Still, I just wonder what the problem is. Maybe it's my version of Angular 2. I'm still on rc5 (have to be for a little while because of other interdependencies).

**Comment by 7Hd** [comment]
If use:

```html
<ckeditor
    [(ngModel)]="model.body"
    [config]="{uiColor: '#99000'}"
    (change)="onChange($event)"
    (ready)="onReady($event)"
    debounce="500" name="body">
</ckeditor>
```

then, you need add `onChange()` and `onReady()` to your component, just like `model.body` for **ngModel**

```ts
class YourComponent {
  // ...
  onChange() { }
  onReady() { }
}
```

**Comment by codyburleson** [comment]
@7Hd, I think that's what I was missing. I was expecting those events to be in the code of the ckeditor component itself, but you've reminded me that I need to implement those two methods in my controller backing the view. Thanks!

**Comment by chymz** [comment]
thanks @7Hd  !
